## Expt.-5: Disease Prediction using Naive Bayes and Neural Network with Comparison of Classifiers
## Name:Jhoshua Coutinho 
## Class: SE AIML  Roll No.11

In [73]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report
import numpy as np
import pandas as pd

In [74]:
# Load dataset
data = load_breast_cancer()

X = data.data
y = data.target

print("Classes:",data.target_names)
# malignant, benign

Classes: ['malignant' 'benign']


In [75]:
df = pd.DataFrame(X)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       569 non-null    float64
 1   1       569 non-null    float64
 2   2       569 non-null    float64
 3   3       569 non-null    float64
 4   4       569 non-null    float64
 5   5       569 non-null    float64
 6   6       569 non-null    float64
 7   7       569 non-null    float64
 8   8       569 non-null    float64
 9   9       569 non-null    float64
 10  10      569 non-null    float64
 11  11      569 non-null    float64
 12  12      569 non-null    float64
 13  13      569 non-null    float64
 14  14      569 non-null    float64
 15  15      569 non-null    float64
 16  16      569 non-null    float64
 17  17      569 non-null    float64
 18  18      569 non-null    float64
 19  19      569 non-null    float64
 20  20      569 non-null    float64
 21  21      569 non-null    float64
 22  22

In [76]:
df.shape

(569, 30)

In [77]:
df.describe()

0           1           2            3           4   \
count  569.000000  569.000000  569.000000   569.000000  569.000000   
mean    14.127292   19.289649   91.969033   654.889104    0.096360   
std      3.524049    4.301036   24.298981   351.914129    0.014064   
min      6.981000    9.710000   43.790000   143.500000    0.052630   
25%     11.700000   16.170000   75.170000   420.300000    0.086370   
50%     13.370000   18.840000   86.240000   551.100000    0.095870   
75%     15.780000   21.800000  104.100000   782.700000    0.105300   
max     28.110000   39.280000  188.500000  2501.000000    0.163400   

               5           6           7           8           9   ...  \
count  569.000000  569.000000  569.000000  569.000000  569.000000  ...   
mean     0.104341    0.088799    0.048919    0.181162    0.062798  ...   
std      0.052813    0.079720    0.038803    0.027414    0.007060  ...   
min      0.019380    0.000000    0.000000    0.106000    0.049960  ...   
25%      0.064920    0.029560    0.020310    0.161900    0.057700  ...   
50%      0.092630    0.061540    0.033500    0.179200    0.061540  ...   
75%      0.130400    0.130700    0.074000    0.195700    0.066120  ...   
max      0.345400    0.426800    0.201200    0.304000    0.097440  ...   

               20          21          22           23          24  \
count  569.000000  569.000000  569.000000   569.000000  569.000000   
mean    16.269190   25.677223  107.261213   880.583128    0.132369   
std      4.833242    6.146258   33.602542   569.356993    0.022832   
min      7.930000   12.020000   50.410000   185.200000    0.071170   
25%     13.010000   21.080000   84.110000   515.300000    0.116600   
50%     14.970000   25.410000   97.660000   686.500000    0.131300   
75%     18.790000   29.720000  125.400000  1084.000000    0.146000   
max     36.040000   49.540000  251.200000  4254.000000    0.222600   

               25          26          27          28          29  
count  569.000000  569.000000  569.000000  569.000000  569.000000  
mean     0.254265    0.272188    0.114606    0.290076    0.083946  
std      0.157336    0.208624    0.065732    0.061867    0.018061  
min      0.027290    0.000000    0.000000    0.156500    0.055040  
25%      0.147200    0.114500    0.064930    0.250400    0.071460  
50%      0.211900    0.226700    0.099930    0.282200    0.080040  
75%      0.339100    0.382900    0.161400    0.317900    0.092080  
max      1.058000    1.252000    0.291000    0.663800    0.207500  

[8 rows x 30 columns]

In [78]:
X_train,X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [79]:
#Logistic Regression
lr = LogisticRegression(max_iter=5000)
lr.fit(X_train, y_train)
pred_lr = lr.predict(X_test)
print("Logistic TestAccuracy:", accuracy_score(y_test, pred_lr))
pred_lr_train = lr.predict(X_train)
print("Logistic TrainAccuracy:", accuracy_score(y_train, pred_lr_train))

Logistic TestAccuracy: 0.9532163742690059
Logistic TrainAccuracy: 0.964824120603015


In [80]:
#Decision Tree
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)
pred_dt = dt.predict(X_test)
print("Decision Tree TestAccuracy:", accuracy_score(y_test, pred_dt))
pred_dt_train = dt.predict(X_train)
print("Decision Tree TrainAccuracy:", accuracy_score(y_train, pred_dt_train))

Decision Tree TestAccuracy: 0.9298245614035088
Decision Tree TrainAccuracy: 1.0


In [81]:
#KNN
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
pred_knn = knn.predict(X_test)
print("KNeighborsClassifier TestAccuracy:", accuracy_score(y_test, pred_knn))
pred_knn_train = knn.predict(X_train)
print("KNeighborsClassifier TrainAccuracy:", accuracy_score(y_train, pred_knn_train))

KNeighborsClassifier TestAccuracy: 0.9064327485380117
KNeighborsClassifier TrainAccuracy: 0.949748743718593


In [82]:
# Naive bayes
NB = GaussianNB()
NB.fit(X_train, y_train)
pred_NB = NB.predict(X_test)
print("GaussianNB TestAccuracy:", accuracy_score(y_test, pred_NB))
pred_NB_train = NB.predict(X_train)
print("GaussianNB TrainAccuracy:", accuracy_score(y_train, pred_NB_train))

GaussianNB TestAccuracy: 0.9415204678362573
GaussianNB TrainAccuracy: 0.9447236180904522


In [83]:
# MLP
MLP = MLPClassifier()
MLP.fit(X_train, y_train)
pred_MLP = MLP.predict(X_test)
print("MLPClassifier TestAccuracy:", accuracy_score(y_test, pred_MLP))
pred_MLP_train = MLP.predict(X_train)
print("MLPClassifier TrainAccuracy:", accuracy_score(y_train, pred_MLP_train))

MLPClassifier TestAccuracy: 0.9415204678362573
MLPClassifier TrainAccuracy: 0.9422110552763819


C:\Users\Jhoshua Coutinho\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [84]:
# Example confusion matrix, Type-I and Type-II error for lr
cm_lr = confusion_matrix(y_test, pred_lr)
print("\nLogistic Regression Confusion Matrix")
print(cm_lr)
TN1, FP1, FN1, TP1 = cm_lr.ravel()
type1_lr = FP1 / (FP1 + TN1) #False positive rate
type2_lr = FN1 / (FN1 + TP1) #False negative rate

print("FP (Type-I):", FP1)
print("FN (Type-II):", FN1)
print("Type-I Error Rate in %:", type1_lr*100)
print("Type-II Error Rate in %:", type2_lr*100)



Logistic Regression Confusion Matrix
[[67  4]
 [ 4 96]]
FP (Type-I): 4
FN (Type-II): 4
Type-I Error Rate in %: 5.633802816901409
Type-II Error Rate in %: 4.0


In [85]:
# Example confusion matrix, Type-I and Type-II error for dt
cm_dt = confusion_matrix(y_test, pred_dt)
print("\nDecision Tree Confusion Matrix")
print(cm_dt)
TN2, FP2, FN2, TP2 = cm_dt.ravel()
type1_dt = FP2 / (FP2 + TN2) #False positive rate
type2_dt = FN2 / (FN2 + TP2) #False negative rate

print("FP (Type-I):", FP2)
print("FN (Type-II):", FN2)
print("Type-I Error Rate in %:", type1_dt*100)
print("Type-II Error Rate in %:", type2_dt*100)


Decision Tree Confusion Matrix
[[66  5]
 [ 7 93]]
FP (Type-I): 5
FN (Type-II): 7
Type-I Error Rate in %: 7.042253521126761
Type-II Error Rate in %: 7.000000000000001


In [86]:
# Example confusion matrix, Type-I and Type-II error for Knn
cm_knn = confusion_matrix(y_test, pred_knn)
print("\nK-Nearest Neighbor Confusion Matrix")
print(cm_knn)
TN3, FP3, FN3, TP3 = cm_knn.ravel()
type1_knn = FP3 / (FP3 + TN3) #False positive rate
type2_knn = FN3 / (FN3 + TP3) #False negative rate

print("FP (Type-I):", FP3)
print("FN (Type-II):", FN3)
print("Type-I Error Rate in %:", type1_knn*100)
print("Type-II Error Rate in %:", type2_knn*100)


K-Nearest Neighbor Confusion Matrix
[[63  8]
 [ 8 92]]
FP (Type-I): 8
FN (Type-II): 8
Type-I Error Rate in %: 11.267605633802818
Type-II Error Rate in %: 8.0


In [87]:
# Example confusion matrix, Type-I and Type-II error for NB
cm_NB = confusion_matrix(y_test, pred_NB)
print("\nNaive bayes Confusion Matrix")
print(cm_NB)
TN4, FP4, FN4, TP4 = cm_NB.ravel()
type1_NB = FP4 / (FP4 + TN4) #False positive rate
type2_NB = FN4 / (FN4 + TP4) #False negative rate

print("FP (Type-I):", FP4)
print("FN (Type-II):", FN4)
print("Type-I Error Rate in %:", type1_NB*100)
print("Type-II Error Rate in %:", type2_NB*100)


Naive bayes Confusion Matrix
[[63  8]
 [ 2 98]]
FP (Type-I): 8
FN (Type-II): 2
Type-I Error Rate in %: 11.267605633802818
Type-II Error Rate in %: 2.0


In [88]:
# Example confusion matrix, Type-I and Type-II error for MLP
cm_MLP = confusion_matrix(y_test, pred_MLP)
print("\nMLPClassifier Confusion Matrix")
print(cm_MLP)
TN5, FP5, FN5, TP5 = cm_MLP.ravel()
type1_MLP = FP5 / (FP5 + TN5) #False positive rate
type2_MLP = FN5 / (FN5 + TP5) #False negative rate

print("FP (Type-I):", FP5)
print("FN (Type-II):", FN5)
print("Type-I Error Rate in %:", type1_MLP*100)
print("Type-II Error Rate in %:", type2_MLP*100)


MLPClassifier Confusion Matrix
[[66  5]
 [ 5 95]]
FP (Type-I): 5
FN (Type-II): 5
Type-I Error Rate in %: 7.042253521126761
Type-II Error Rate in %: 5.0


In [93]:
# Calculating values for LR

precision = precision_score(y_test, pred_lr)
recall = recall_score(y_test, pred_lr)
f1 = f1_score(y_test,pred_lr)
roc = roc_auc_score(y_test,pred_lr)
print("Precision:",precision)
print("f1:",f1)
print("roc:",roc)
print("recall:",recall)

Precision: 0.96
f1: 0.96
roc: 0.9518309859154929
recall: 0.96
